INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Algoritmul ZOH discretizeazÄƒ sisteme continue Ã®n paÈ™i', 'PaÈ™ii pentru discretizarea unui sistem continuu H(s) folosind metoda ZOH: rÄƒspuns la treaptÄƒ, eÈ™antionare, calcul impuls discret, transformata Z', ARRAY['Sisteme Automate'], 'algorithm', 'CURS 5 - SA_2026.pdf', 'supported');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Arhitectura KNX este descentralizatÄƒ pe bazÄƒ de evenimente cu transmisie serialÄƒ prin cablu BUS', 'Arhitectura sistemului KNX este descentralizatÄƒ, pe bazÄƒ de evenimente, cu transmisie serialÄƒ a telegramelor prin cablu BUS la 24V, acces CSMA È™i confirmare la recepÈ›ie', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C11-C13 - Conceptul BMS si standardul KNX.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Arhitectura unui sistem antiefracÈ›ie cuprinde centralÄƒ, detectori, tastaturi, sirene È™i acumulatori', 'Arhitectura unui sistem antiefracÈ›ie are ca element central panoul de control (centrala) care gestioneazÄƒ detectorii de miÈ™care, contactele magnetice, tastaturile, sirenele, butoanele de panicÄƒ È™i acumulatorii', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C9 - Sisteme antiefractie.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ARP asociazÄƒ adrese IP cu MAC, iar ICMP diagnosticheazÄƒ conectivitatea Ã®n reÈ›ea', 'ARP asociazÄƒ adrese IP (nivel 3) cu adrese MAC (nivel 2) Ã®n reÈ›eaua localÄƒ, iar ICMP permite diagnosticarea conectivitÄƒÈ›ii È™i raportarea erorilor Ã®n reÈ›elele IP', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C5_2025_l3_retea_2_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Asincronismul Ã®n JavaScript foloseÈ™te Promises È™i Fetch API pentru operaÈ›ii neblocante', 'Asincronismul Ã®n JavaScript rezolvÄƒ limitarea single-threaded prin mecanisme non-blocking: Callback-uri (model vechi), Promises (obiecte care reprezintÄƒ valori viitoare) È™i Async/Await (sintaxÄƒ simplificatÄƒ), cu Fetch API pentru cereri HTTP', ARRAY['Tehnologii Web'], 'definition', 'Curs 7_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Automatica este È™tiinÈ›a conducerii proceselor fÄƒrÄƒ intervenÈ›ia directÄƒ a omului', 'Automatica studiazÄƒ principiile È™i aparatele pentru conducerea proceselor tehnice fÄƒrÄƒ intervenÈ›ia directÄƒ a omului; automatizarea este aplicarea practicÄƒ', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Automatizarea ClÄƒdirilor', 'HartÄƒ-materie â€” Automatizarea ClÄƒdirilor, AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', NULL, 'hartÄƒ-materie', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('BAN este o reÈ›ea de dispozitive purtabile Ã®n imediata apropiere a utilizatorului', 'BAN (Body Area Network) cuprinde dispozitive purtabile (wearable) sau implantabile, Ã®n curs de dezvoltare odatÄƒ cu reÈ›elele de senzori wireless (WSN)', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C1_2025_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('BMS este sistemul centralizat de monitorizare, control È™i optimizare a instalaÈ›iilor clÄƒdirii', 'BMS (Building Management System) este sistemul centralizat care monitorizeazÄƒ, controleazÄƒ È™i optimizeazÄƒ toate instalaÈ›iile tehnice ale clÄƒdirii: HVAC, iluminat, securitate, control acces È™i management energetic', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C11-C13 - Conceptul BMS si standardul KNX.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Bootstrap Grid este un sistem de layout responsive cu 12 coloane pentru design mobile-first', 'Sistemul de grid Bootstrap este construit pe Flexbox cu 12 coloane È™i 6 niveluri responsive (xs, sm, md, lg, xl, xxl), permiÈ›Ã¢nd layout-uri care se adapteazÄƒ automat la dimensiunea ecranului', ARRAY['Tehnologii Web'], 'definition', 'Curs 5_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('CAN cuprinde mai multe LAN-uri Ã®ntr-o arie de campus', 'CAN (Campus Area Network) acoperÄƒ o arie geograficÄƒ de diferite dimensiuni È™i cuprinde mai multe LAN-uri interconectate', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C1_2025_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Clasificarea reÈ›elelor se face dupÄƒ aria geograficÄƒ', 'ReÈ›elele se clasificÄƒ Ã®n funcÈ›ie de aria geograficÄƒ: BAN, PAN, LAN, CAN, MAN, WAN â€” de la corpul uman la continente', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C1_2025_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ClÄƒdirea inteligentÄƒ integreazÄƒ toate subsistemele Ã®ntr-un sistem unic controlabil', 'ClÄƒdirea inteligentÄƒ integreazÄƒ controlul iluminat, temperaturÄƒ, sonorizare, alarmare, irigare etc. Ã®ntr-un singur sistem, controlabil local sau remote', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ComunicaÈ›iile unicast, broadcast È™i multicast definesc moduri de adresare Ã®n reÈ›ea', 'ComunicaÈ›iile de reÈ›ea se clasificÄƒ Ã®n unicast (1:1), broadcast (1:toÈ›i din reÈ›ea) È™i multicast (1:grup), fiecare cu adrese È™i mecanisme specifice de livrare a pachetelor', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C2_2025_l_fizic_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Criptografia È™i VPN-urile asigurÄƒ confidenÈ›ialitatea È™i integritatea datelor Ã®n reÈ›ea', 'Criptografia simetricÄƒ È™i asimetricÄƒ asigurÄƒ confidenÈ›ialitatea È™i autenticitatea datelor, iar TLS, IPsec È™i VPN-urile protejeazÄƒ comunicaÈ›iile Ã®n reÈ›elele IP', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C8_2025_securitate.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('CSS este limbajul de stilizare vizualÄƒ a paginilor web', 'CSS (Cascading Style Sheets) este limbajul care controleazÄƒ aspectul vizual al paginilor web: culori, fonturi, spaÈ›ieri, poziÈ›ionare, animaÈ›ii È™i design responsive', ARRAY['Tehnologii Web'], 'definition', 'Curs 4_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('CSS Flexbox este un sistem de layout unidirecÈ›ional pentru distribuirea spaÈ›iului Ã®ntre elemente', 'CSS Flexbox (Flexible Box) este un modul de layout unidirecÈ›ional care distribuie eficient spaÈ›iul Ã®ntre elementele unui container, permiÈ›Ã¢nd aliniere, ordonare È™i redimensionare flexibilÄƒ, indiferent de dimensiunile iniÈ›iale ale acestora', ARRAY['Tehnologii Web'], 'definition', 'Curs 5_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('CSS Grid este un sistem de layout bidimensional cu rÃ¢nduri, coloane È™i zone definite', 'CSS Grid Layout este un sistem de layout bidimensional care organizeazÄƒ elemente pe rÃ¢nduri È™i coloane simultan, spre deosebire de Flexbox care este unidirecÈ›ional, oferind control precis asupra plasÄƒrii È™i dimensiunilor', ARRAY['Tehnologii Web'], 'definition', 'Curs 5_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Discretizarea sistemelor continue transformÄƒ H(s) Ã®n H(z)', 'Transformarea sistemelor continue din domeniul Laplace Ã®n sisteme discrete Ã®n domeniul z, necesarÄƒ pentru implementarea controlerelor pe microcontrolere sau DSP-uri', ARRAY['Sisteme Automate'], 'definition', 'CURS 5 - SA_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Discretizarea ZOH pentru sistem de ordinul I are formulÄƒ directÄƒ', 'Pentru H(s) = 1/(s+a), discretizarea ZOH este H(z) = (1-e^(-aT))/(z-e^(-aT))', ARRAY['Sisteme Automate'], 'formula', 'CURS 5 - SA_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('DNS este un sistem ierarhic distribuit care traduce nume de domenii Ã®n adrese IP', 'DNS este un sistem ierarhic distribuit care traduce nume de domenii Ã®n adrese IP, organizat pe domenii È™i zone cu servere autoritare È™i recursive', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C7_2025_l5-l7_aplicatii.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('DOM permite manipularea dinamicÄƒ a elementelor È™i evenimentelor paginii web', 'DOM (Document Object Model) este reprezentarea paginii web ca arbore de noduri accesibil dinamic prin JavaScript, permiÈ›Ã¢nd selectarea, modificarea È™i reacÈ›ia la evenimente ale elementelor HTML', ARRAY['Tehnologii Web'], 'definition', 'Curs 7_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Domotica transformÄƒ locuinÈ›a Ã®ntr-un spaÈ›iu inteligent prin gestionarea automatÄƒ a instalaÈ›iilor', 'Domotica este tehnologia care transformÄƒ o locuinÈ›Äƒ Ã®n spaÈ›iu inteligent prin gestionarea automatÄƒ a iluminatului, climei, draperiilor, sonorizÄƒrii, irigaÈ›iilor È™i securitÄƒÈ›ii', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C7 - Domotica si niveluri de automatizare.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Fibra opticÄƒ utilizeazÄƒ reflexia internÄƒ pentru transmisia datelor prin impulsuri luminoase', 'Fibra opticÄƒ transmite date sub formÄƒ de impulsuri luminoase prin miez de sticlÄƒ sau plastic, oferind imunitate la interferenÈ›e electromagnetice, distanÈ›e mari È™i rate de transfer foarte ridicate', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C2_2025_l_fizic_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Firewall-urile È™i sistemele IDS/IPS protejeazÄƒ reÈ›elele prin filtrarea È™i inspectarea traficului', 'Firewall-urile filtreazÄƒ traficul pe bazÄƒ de reguli predefinite, iar sistemele IDS/IPS inspecteazÄƒ conÈ›inutul pachetelor la toate nivelurile pentru a detecta È™i preveni atacurile', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C8_2025_securitate.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('FuncÈ›ia StayD menÈ›ine sistemul de alarmÄƒ permanent armat cu dezarmare temporarÄƒ la intrare', 'FuncÈ›ia StayD menÈ›ine sistemul de securitate permanent armat, cu dezarmare temporarÄƒ doar a zonelor de intrare/ieÈ™ire È™i rearmare automatÄƒ dupÄƒ Ã®nchidere', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C9 - Sisteme antiefractie.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('FuncÈ›iile PHP permit organizarea modularÄƒ a codului cu parametri tipaÈ›i', 'FuncÈ›iile PHP sunt blocuri de cod reutilizabile, cu type hints, parametri cu valori implicite, argumente numite (PHP 8+), union types, variadice, arrow functions (PHP 7.4+), È™i suport pentru funcÈ›ii anonime cu captarea variabilelor prin use', ARRAY['Tehnologii Web'], 'definition', 'Curs_8_9_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('HTML a fost creat de Tim Berners-Lee la CERN Ã®n 1989 È™i a evoluat prin versiuni majore', 'HTML a fost inventat de Tim Berners-Lee la CERN Ã®n 1989; prima versiune HTML 1.0 a fost lansatÄƒ Ã®n 1993', ARRAY['Tehnologii Web'], 'definition', 'Curs 2-3_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('HTML este limbajul de marcare hypertext pentru structurarea paginilor web', 'HTML (HyperText Markup Language) este limbajul standard de marcare pentru crearea paginilor web, definind structura È™i organizarea conÈ›inutului prin etichete', ARRAY['Tehnologii Web'], 'definition', 'Curs 2-3_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('InteligenÈ›a artificialÄƒ optimizeazÄƒ consumul energetic È™i personalizeazÄƒ experienÈ›a Ã®n clÄƒdirile inteligente', 'InteligenÈ›a artificialÄƒ Ã®n automatizarea clÄƒdirilor permite analizÄƒ predictivÄƒ pentru mentenanÈ›Äƒ proactivÄƒ, optimizare energeticÄƒ, personalizarea confortului È™i securitate Ã®mbunÄƒtÄƒÈ›itÄƒ', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C2-C6 - Clasificarea sistemelor de automatizare a cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('InteligenÈ›Äƒ ArtificialÄƒ', 'HartÄƒ-materie â€” InteligenÈ›Äƒ ArtificialÄƒ, AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', NULL, 'hartÄƒ-materie', 'vault', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Internetul este o reÈ›ea globalÄƒ de reÈ›ele interconectate prin TCP/IP', 'Internetul este o reÈ›ea globalÄƒ unificatÄƒ de calculatoare interconectate prin stiva TCP/IP', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('IPv6 extinde adresarea la 128 de biÈ›i cu notaÈ›ie hexazecimalÄƒ', 'IPv6 utilizeazÄƒ 128 de biÈ›i È™i notaÈ›ie hexazecimalÄƒ (8 grupÄƒri Ã— 16 biÈ›i), Ã®nlocuind clasele de adrese cu prefixe È™i introducÃ¢nd adrese anycast pe lÃ¢ngÄƒ unicast È™i multicast', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C2_2025_l_fizic_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('JavaScript este un limbaj de programare interpretat pentru interactivitatea paginilor web', 'JavaScript este un limbaj de programare interpretat, multi-platformÄƒ, single-threaded, care ruleazÄƒ Ã®n browser (client-side) sau pe server (cu Node.js), utilizat pentru a crea conÈ›inut dinamic È™i interactiv Ã®n paginile web', ARRAY['Tehnologii Web'], 'definition', 'Curs 6_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('KNX este standardul internaÈ›ional deschis pentru automatizarea clÄƒdirilor, provenit din EIB, BatiBUS È™i EHS', 'KNX este un standard internaÈ›ional deschis (EN 50090, ISO/IEC 14543) pentru automatizarea clÄƒdirilor, rezultat din unirea EIB, BatiBUS È™i EHS, administrat de AsociaÈ›ia Konnex', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C11-C13 - Conceptul BMS si standardul KNX.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('LAN este o reÈ›ea localÄƒ cu arie geograficÄƒ restrÃ¢nsÄƒ', 'LAN (Local Area Network) acoperÄƒ o arie geograficÄƒ restrÃ¢nsÄƒ (locuinÈ›Äƒ, birou, departament) cu management comun È™i politici uniforme', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C1_2025_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Metoda Tustin aproximeazÄƒ s prin transformarea biliniarÄƒ', 'Metoda Tustin (transformare biliniarÄƒ) transformÄƒ sistemele continue Ã®n discrete prin substituÈ›ia s = (2/T)*(z-1)/(z+1), pÄƒstrÃ¢nd comportamentul general al sistemului', ARRAY['Sisteme Automate'], 'definition', 'CURS 5 - SA_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Microcontrolere', 'HartÄƒ-materie â€” Microcontrolere, AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', NULL, 'hartÄƒ-materie', 'vault', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Modelul client-server partajeazÄƒ procesarea Ã®ntre furnizori È™i solicitanÈ›i de servicii', 'Modelul client-server partajeazÄƒ procesarea Ã®ntre furnizori de servicii (servere) È™i solicitanÈ›i (clienÈ›i), unde clientul iniÈ›iazÄƒ comunicarea printr-o sesiune limitatÄƒ Ã®n timp', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C7_2025_l5-l7_aplicatii.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('MÄƒrimea reglatÄƒ, de execuÈ›ie È™i perturbatoare sunt mÄƒrimile fundamentale ale reglÄƒrii', 'MÄƒrimea reglatÄƒ (y) se menÈ›ine la valoarea prescrisÄƒ, mÄƒrimea de execuÈ›ie (m) influenÈ›eazÄƒ reglata, perturbaÈ›iile (p) cauzeazÄƒ abateri', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Nivelul fizic OSI defineÈ™te specificaÈ›ii pentru transmisia de biÈ›i prin medii de comunicaÈ›ie', 'Nivelul fizic (nivelul 1 OSI) transportÄƒ biÈ›i Ã®ntre echipamente, definind specificaÈ›ii electrice, mecanice, procedurale È™i funcÈ›ionale pentru activarea È™i menÈ›inerea legÄƒturilor fizice', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C2_2025_l_fizic_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Nivelul legÄƒturÄƒ de date transmite cadre cu adrese MAC Ã®ntre noduri din aceeaÈ™i reÈ›ea', 'Nivelul legÄƒturÄƒ de date (nivelul 2 OSI) transmite cadre (frames) Ã®ntre noduri din aceeaÈ™i reÈ›ea localÄƒ, utilizÃ¢nd adrese MAC pentru identificarea sursei È™i destinaÈ›iei', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C3_2025_l_legatura_date_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Nivelul reÈ›ea realizeazÄƒ rutarea pachetelor pe baza adreselor IP', 'Nivelul reÈ›ea realizeazÄƒ rutarea pachetelor Ã®ntre reÈ›ele diferite pe baza adreselor IP, utilizÃ¢nd tabele de rutare pentru a determina calea optimÄƒ cÄƒtre destinaÈ›ie', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C4_2025_l3_retea_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Nivelul transport segmenteazÄƒ È™i multiplexeazÄƒ datele pe bazÄƒ de porturi', 'Nivelul transport segmenteazÄƒ È™i multiplexeazÄƒ datele de la aplicaÈ›ii pe bazÄƒ de porturi, iar socket-ul (IP:port) identificÄƒ unic o aplicaÈ›ie pe o staÈ›ie Ã®n reÈ›ea', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C6_2025_l4_transport_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Nivelurile superioare OSI asigurÄƒ interfaÈ›a cu utilizatorul È™i gestionarea dialogurilor', 'Nivelurile superioare OSI (aplicaÈ›ie, prezentare, sesiune) asigurÄƒ interfaÈ›a cu utilizatorul, transformarea formatelor de date È™i gestionarea dialogurilor Ã®ntre aplicaÈ›ii', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C7_2025_l5-l7_aplicatii.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Nivelurile de achiziÈ›ie È™i prelucrare a datelor Ã®n clÄƒdirile inteligente sunt cÃ¢mp, automatizare È™i management', 'Modelul HES-C3B defineÈ™te trei nivele de achiziÈ›ie È™i prelucrare a datelor Ã®n clÄƒdirile inteligente: nivel de cÃ¢mp (senzori), nivel de automatizare (controlere) È™i nivel de management (SCADA)', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C7 - Domotica si niveluri de automatizare.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('PHP este un limbaj de scripting server-side pentru generarea paginilor web dinamice', 'PHP (PHP: Hypertext Preprocessor) este un limbaj de scripting server-side, open-source, cu tipizare dinamicÄƒ, incorporabil direct Ã®n HTML, care genereazÄƒ dinamic conÈ›inut web È™i poate accesa baze de date È™i fiÈ™iere pe server', ARRAY['Tehnologii Web'], 'definition', 'Curs_8_9_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('PHP manipuleazÄƒ È™irurile de caractere cu patru moduri de delimitare È™i funcÈ›ii specifice', 'PHP oferÄƒ patru moduri de definire a È™irurilor â€” ghilimele simple (literal), ghilimele duble (cu interpolare), heredoc (multi-linie cu interpolare) È™i nowdoc (multi-linie fÄƒrÄƒ interpolare) â€” plus funcÈ›ii built-in pentru prelucrare: concatenare, cÄƒutare, Ã®nlocuire, extragere È™i transformare', ARRAY['Tehnologii Web'], 'definition', 'Curs 10-11_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('PHP necesitÄƒ extensia mbstring pentru manipularea corectÄƒ a caracterelor UTF-8', 'Deoarece funcÈ›iile standard PHP lucreazÄƒ byte cu byte (nu caracter cu caracter), extensia mbstring (multi-byte string) este necesarÄƒ pentru manipularea corectÄƒ a caracterelor UTF-8 precum Äƒ, Ã¢, Ã®, È™, È› sau emoji-uri', ARRAY['Tehnologii Web'], 'definition', 'Curs 10-11_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('PHP suportÄƒ tipuri de date dinamice, operatori È™i funcÈ›ii pentru prelucrarea datelor', 'PHP oferÄƒ 8 tipuri de date (integer, float, string, boolean, array, object, null, resource) cu tipizare dinamicÄƒ, conversii automate (type juggling) È™i explicite (type casting), operatori complecÈ™i È™i constante pentru stocarea valorilor neschimbÄƒtoare', ARRAY['Tehnologii Web'], 'definition', 'Curs_8_9_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ProprietÄƒÈ›ile CSS de formatare vizualÄƒ controleazÄƒ fundalul, textul, fonturile, linkurile, listele È™i tabelele', 'CSS oferÄƒ proprietÄƒÈ›i specializate pentru fiecare aspect vizual: background (culoare, imagine, repetare, poziÈ›ie), text (culoare, aliniere, decorare, transformare, spaÈ›iere), font (familie, stil, dimensiune, greutate), linkuri (pseudo-clase), liste (marcatori) È™i tabele (chenar, colapsare, dimensiuni)', ARRAY['Tehnologii Web'], 'definition', 'Curs 4_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Protocoalele de comunicare Lonworks, BACnet, KNX È™i OPC standardizeazÄƒ automatizarea clÄƒdirilor', 'Protocoalele de comunicare Lonworks, BACnet, KNX/EIB È™i OPC standardizeazÄƒ schimbul de date Ã®ntre echipamentele de automatizare ale clÄƒdirilor, asigurÃ¢nd interoperabilitatea Ã®ntre producÄƒtori diferiÈ›i', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C10 - Protocoale de comunicatie.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Protocoalele deschise LON, BACnet È™i EIB asigurÄƒ interoperabilitatea Ã®ntre echipamentele de automatizare', 'Protocoalele deschise LON (Local Operating Network), BACnet (Building Automation Control Network) È™i EIB (European Installation Bus) permit interoperabilitatea echipamentelor indiferent de producÄƒtor', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C14 - Retele de senzori wireless.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Protocolul IP oferÄƒ un serviciu best-effort neorientat pe conexiune la nivelul reÈ›ea', 'Protocolul IP oferÄƒ un serviciu best-effort neorientat pe conexiune la nivelul reÈ›ea, iar antetul IPv4 conÈ›ine cÃ¢mpuri esenÈ›iale precum TTL, adrese sursÄƒ/destinaÈ›ie È™i checksum', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C5_2025_l3_retea_2_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Protocolul BACnet defineÈ™te obiecte È™i servicii standardizate pentru controlul sistemelor de clÄƒdiri', 'BACnet defineÈ™te obiecte standardizate (AnalogInput, BinaryOutput, Device, Schedule) È™i servicii de comunicaÈ›ie (ReadProperty, WriteProperty, Who-Is, I-Am) pentru controlul sistemelor de clÄƒdiri', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C10 - Protocoale de comunicatie.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Protocolul OPC permite interoperabilitatea Ã®ntre aplicaÈ›ii È™i echipamente de automatizare', 'OPC (OLE for Process Control) eliminÄƒ conflictele de drivere È™i permite integrarea echipamentelor de la producÄƒtori diferiÈ›i Ã®ntr-o singurÄƒ platformÄƒ Windows de monitorizare È™i control', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C10 - Protocoale de comunicatie.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Reglarea automatÄƒ menÈ›ine sau modificÄƒ o mÄƒrime fizicÄƒ dupÄƒ o lege prescrisÄƒ', 'Reglarea automatÄƒ comparÄƒ valoarea mÄƒsuratÄƒ cu valoarea de consemn È™i acÈ›ioneazÄƒ pentru anularea abaterii', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('RetelisticÄƒ', 'HartÄƒ-materie â€” ReÈ›ele de Calculatoare, AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', NULL, 'hartÄƒ-materie', 'RC_C1_2025_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ReÈ›eaua de calculatoare este un set de dispozitive care comunicÄƒ Ã®ntre ele', 'O reÈ›ea de calculatoare este un set de dispozitive de reÈ›ea interconectate care pot comunica Ã®ntre ele prin protocoale, medii de comunicaÈ›ie È™i topologii specifice', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C1_2025_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ReÈ›elele de senzori wireless sunt formate din noduri autonome cu consum redus de energie', 'ReÈ›elele de senzori wireless (WSN) sunt formate din noduri senzore autonome cu consum redus de energie, care mÄƒsoarÄƒ, proceseazÄƒ È™i comunicÄƒ date prin unde radio', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C14 - Retele de senzori wireless.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Router-ul Cisco are memorii specializate È™i moduri de operare pentru configurare', 'Router-ul Cisco este un dispozitiv de nivel 3 cu memorii specializate (RAM, ROM, Flash, NVRAM) È™i moduri de operare (exec, privileged exec, configure, interface) pentru configurarea reÈ›elei', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C4_2025_l3_retea_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Schema bloc a unui SRA conÈ›ine regulator, element de execuÈ›ie È™i reacÈ›ie', 'Schema tipicÄƒ SRA: element de intrare (E) â†’ element de comparaÈ›ie (EC) â†’ regulator (R) â†’ element de execuÈ›ie (EE) â†’ instalaÈ›ia automatizatÄƒ (IA) â†’ reacÈ›ie', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Securitatea reÈ›elelor implicÄƒ identificarea ameninÈ›Äƒrilor È™i protecÈ›ia Ã®mpotriva atacurilor', 'Securitatea reÈ›elelor se bazeazÄƒ pe identificarea ameninÈ›Äƒrilor È™i vulnerabilitÄƒÈ›ilor, iar atacurile comune includ DoS/DDoS, phishing, malware, spoofing È™i social engineering', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C8_2025_securitate.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Securizarea dispozitivelor Cisco implicÄƒ parole, criptare È™i control al accesului', 'Securizarea dispozitivelor Cisco implicÄƒ setarea de parole pentru consolÄƒ È™i acces remote, criptarea parolelor, timeout-uri, liste de control acces È™i utilizatori cu niveluri de privilegii', ARRAY['RetelisticÄƒ'], 'algorithm', 'RC_C8_2025_securitate.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Senzorii activi genereazÄƒ semnal electric iar senzorii pasivi modificÄƒ o impedanÈ›Äƒ', 'Senzorii activi (termoelectrici, piezoelectrici, fotovoltaici) genereazÄƒ semnal electric, iar senzorii pasivi (rezistivi, capacitivi, inductivi) modificÄƒ o impedanÈ›Äƒ sub acÈ›iunea mÄƒsurandului', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C8 - Notiuni fundamentale privind senzorii utilizati in cladirile inteligente.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Senzorul converteÈ™te mÄƒrimea fizicÄƒ mÄƒsuratÄƒ Ã®ntr-un semnal electric prelucrabil', 'Senzorul este elementul care transformÄƒ fenomenul de mÄƒsurat (temperaturÄƒ, presiune, luminÄƒ, forÈ›Äƒ) Ã®ntr-o caracteristicÄƒ electricÄƒ â€” sarcinÄƒ, tensiune, curent sau impedanÈ›Äƒ', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C8 - Notiuni fundamentale privind senzorii utilizati in cladirile inteligente.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Senzorul inteligent integreazÄƒ microprocesor È™i interfaÈ›Äƒ de comunicaÈ›ie pentru prelucrare localÄƒ', 'Senzorul inteligent cuprinde pe aceeaÈ™i structurÄƒ senzorul principal, senzori secundari de compensare, microprocesor, circuite de condiÈ›ionare È™i interfaÈ›Äƒ bidirecÈ›ionalÄƒ de comunicaÈ›ie', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C8 - Notiuni fundamentale privind senzorii utilizati in cladirile inteligente.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sisteme Automate', 'HartÄƒ-materie â€” Sisteme Automate (SA), AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', ARRAY[''], 'hartÄƒ-materie', 'CURS 5 - SA_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sisteme de Reglare AutomatÄƒ', 'HartÄƒ-materie â€” Sisteme de Reglare AutomatÄƒ, AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', NULL, 'hartÄƒ-materie', 'vault', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemele de comandÄƒ automatÄƒ nu controleazÄƒ Ã®ndeplinirea legii date', 'Sistemele de comandÄƒ automatÄƒ realizeazÄƒ o lege de variaÈ›ie fÄƒrÄƒ a controla Ã®ndeplinirea efectivÄƒ â€” funcÈ›ioneazÄƒ Ã®n circuit deschis', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemele de reglare automatÄƒ comparÄƒ valoarea realÄƒ cu cea prescrisÄƒ', 'SRA comparÄƒ mÄƒrimea de ieÈ™ire cu valoarea prescrisÄƒ È™i acÈ›ioneazÄƒ prin mÄƒrimea de execuÈ›ie pentru a aduce ieÈ™irea la valoarea doritÄƒ â€” sistem Ã®n circuit Ã®nchis', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemele antiefracÈ›ie detecteazÄƒ pÄƒtrunderea neautorizatÄƒ prin senzori perimetrali È™i de interior', 'Sistemele electronice de securitate descurajeazÄƒ È™i detecteazÄƒ pÄƒtrunderea neautorizatÄƒ prin detectori de miÈ™care IR È™i microunde, contacte magnetice, bariere IR, detectoare de geam spart È™i senzori de vibraÈ›ie', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C9 - Sisteme antiefractie.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemele de automatizare ale clÄƒdirilor se clasificÄƒ pe subsisteme funcÈ›ionale interconectate', 'Sistemele de automatizare ale clÄƒdirilor se clasificÄƒ pe subsisteme interconectate: HVAC, iluminat, control ferestre/jaluzele, comunicaÈ›ii date-voce, distribuÈ›ie TV, multimedia, monitorizare electricÄƒ, surse de rezervÄƒ, apÄƒ, irigaÈ›ii, anti-Ã®ngheÈ›, management resurse È™i deÈ™euri', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C2-C6 - Clasificarea sistemelor de automatizare a cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemul automat este ansamblul instalaÈ›iei automatizate È™i echipamentului de automatizare', 'Sistemul automat (SA) = instalaÈ›ia automatizatÄƒ (procesul condus) + echipamentul de automatizare (dispozitivul de conducere)', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C1 - Introducere in Cladiri inteligente - Automatizarea cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemul de comunicaÈ›ii date-voce asigurÄƒ infrastructura de reÈ›ea necesarÄƒ operÄƒrii clÄƒdirii inteligente', 'Sistemul de comunicaÈ›ii date-voce asigurÄƒ infrastructura de reÈ›ea cu switch-uri, servere, rack-uri È™i prize de date, monitorizatÄƒ prin Sistemul de Monitorizare È™i Control al ClÄƒdirii', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C2-C6 - Clasificarea sistemelor de automatizare a cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Sistemul de surse de rezervÄƒ cu UPS È™i generator garanteazÄƒ continuitatea alimentÄƒrii', 'Sistemul surselor de rezervÄƒ asigurÄƒ continuitatea alimentÄƒrii echipamentelor critice prin controler UPS cu baterii È™i generator, cu selecÈ›ie automatÄƒ a consumatorilor vitali', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C2-C6 - Clasificarea sistemelor de automatizare a cladirilor.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Software-ul ETS este instrumentul standard de configurare È™i programare a sistemelor KNX', 'ETS (Engineering Tool Software) este instrumentul standard de configurare, programare È™i diagnozÄƒ pentru sistemele KNX, compatibil cu toÈ›i producÄƒtorii È™i cu versiunile anterioare', ARRAY['Automatizarea ClÄƒdirilor'], 'definition', 'C11-C13 - Conceptul BMS si standardul KNX.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Subnetarea IPv4 Ã®mparte un spaÈ›iu de adrese Ã®n subreÈ›ele mai mici', 'Subnetarea IPv4 Ã®mparte un spaÈ›iu de adrese Ã®n subreÈ›ele mai mici pe baza mÄƒÈ™tii de reÈ›ea, facilitÃ¢nd securitatea, administrarea È™i prevenÈ›ia adreselor duplicate', ARRAY['RetelisticÄƒ'], 'algorithm', 'RC_C3_2025_l_legatura_date_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Switch-ul comutÄƒ cadre pe baza tabelei CAM È™i delimiteazÄƒ domenii de coliziune', 'Switch-ul comutÄƒ cadre pe baza tabelei CAM, Ã®nvaÈ›Äƒ dinamic adresele MAC È™i delimiteazÄƒ domenii de coliziune, dar extinde domeniile de broadcast', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C3_2025_l_legatura_date_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Tabela de rutare conÈ›ine rute pentru forwardarea pachetelor Ã®ntre reÈ›ele', 'Tabela de rutare stocheazÄƒ rute direct conectate È™i rute la distanÈ›Äƒ (statice sau dinamice), iar selectarea rutei se face pe baza mÄƒÈ™tii, distanÈ›ei administrative È™i metricii', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C4_2025_l3_retea_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('TCP stabileÈ™te conexiuni sigure prin three-way handshake, iar UDP oferÄƒ un serviciu rapid fÄƒrÄƒ conexiune', 'TCP este un protocol orientat pe conexiune care asigurÄƒ livrarea sigurÄƒ a datelor prin three-way handshake, numere de secvenÈ›Äƒ È™i control al fluxului, spre deosebire de UDP care este best-effort', ARRAY['RetelisticÄƒ'], 'definition', 'RC_C6_2025_l4_transport_fara_quizz.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Tehnologii Web', 'HartÄƒ-materie â€” Tehnologii Web, AutomaticÄƒ È™i InformaticÄƒ AplicatÄƒ Anul III', NULL, 'hartÄƒ-materie', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Transformarea Tustin pentru sistem de ordinul I se aplicÄƒ direct', 'Pentru H(s) = 1/(s+1) cu T=1, discretizarea Tustin produce H(z) = (1+z^{-1})/(3(1 - z^{-1}/3))', ARRAY['Sisteme Automate'], 'formula', 'CURS 5 - SA_2026.pdf', 'supported');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Un pachet HTTP traverseazÄƒ Ã®ntreaga stivÄƒ OSI prin Ã®ncapsulare È™i rutare succesivÄƒ', 'Un pachet HTTP traverseazÄƒ Ã®ntreaga stivÄƒ OSI de la expeditor la receptor printr-un proces de Ã®ncapsulare succesivÄƒ, rutare Ã®ntre subreÈ›ele È™i decapsulare la destinaÈ›ie', ARRAY['RetelisticÄƒ'], 'example', 'RC_C9_recapitulare.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('URI identificÄƒ uniform resursele pe Web', 'URI (Uniform Resource Identifier) este un È™ir de caractere care identificÄƒ uniform o resursÄƒ pe Web â€” URL + URN', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Variabilele, operatorii È™i structurile de control stau la baza logicii JavaScript', 'JavaScript oferÄƒ tipuri de date primitive (number, string, boolean, null, undefined, symbol, bigint) È™i de referinÈ›Äƒ (object, array, function), operatori aritmetici, logici, de comparaÈ›ie È™i structuri de control condiÈ›ionale È™i repetitive', ARRAY['Tehnologii Web'], 'definition', 'Curs 6_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Viitorul HTML include design mobil-first, responsivitate È™i integrare cu VR È™i IoT', 'HTML evolueazÄƒ spre mobil-first, responsivitate, integrare cu VR È™i IoT pentru aplicaÈ›ii web moderne', ARRAY['Tehnologii Web'], 'definition', 'Curs 2-3_TW_2026.pdf', 'supported');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Web 1.0 a Ã®nsemnat pagini statice È™i conÈ›inut informativ', 'Web 1.0 (1994-2000) a fost caracterizat de pagini statice cu conÈ›inut informativ, puÈ›inÄƒ interactivitate â€” site-uri tip broÈ™urÄƒ Ã®n HTML simplu', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Web 2.0 a adus conÈ›inut generat de utilizatori È™i aplicaÈ›ii interactive', 'Web 2.0 (2000-2010) a introdus conÈ›inut generat de utilizatori, aplicaÈ›ii web dinamice, interactivitate ridicatÄƒ â€” reÈ›ele sociale, bloguri, YouTube, AJAX, JavaScript avansat', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Web modern include AI, cloud, API-uri REST È™i aplicaÈ›ii SPA', 'Web-ul modern (2010-prezent) include aplicaÈ›ii cloud, AI, personalizare, API-uri REST, aplicaÈ›ii SPA (React/Angular/Vue), PWA, IoT È™i blockchain', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Web-ul a fost creat de Tim Berners-Lee la CERN Ã®n 1989', 'Tim Berners-Lee a propus sistemul de gestionare a documentelor È™tiinÈ›ifice prin hipertext la CERN Ã®n 1989, consideratÄƒ data oficialÄƒ a conceperii WWW', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('WWW este un serviciu distribuit de informaÈ›ii hypermedia peste Internet', 'WWW este un serviciu de informaÈ›ii distribuit, bazat pe hipertext È™i hypermedia, care funcÈ›ioneazÄƒ peste infrastructura Internetului', ARRAY['Tehnologii Web'], 'definition', 'Curs 1_TW_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('Zero-Order Hold menÈ›ine constantÄƒ ultima valoare eÈ™antionatÄƒ', 'ZOH este un model matematic al modului Ã®n care un DAC reconstruieÈ™te un semnal analogic din valori discrete, menÈ›inÃ¢nd constantÄƒ ultima valoare Ã®ntre eÈ™antioane', ARRAY['Sisteme Automate'], 'definition', 'CURS 5 - SA_2026.pdf', 'established');
INSERT INTO public.concepts (title, description, materii, type, source, confidence) VALUES ('ZOH vs Tustin diferÄƒ prin abordare timp vs frecvenÈ›Äƒ', 'ZOH modeleazÄƒ sistemul fizic Ã®n timp (Ã®ntÃ¢rziere explicitÄƒ), Tustin aproximeazÄƒ matematic sistemul Ã®n frecvenÈ›Äƒ (fÄƒrÄƒ Ã®ntÃ¢rziere explicitÄƒ)', ARRAY['Sisteme Automate'], 'example', 'CURS 5 - SA_2026.pdf', 'supported');INSERT INTO public.concepts (id, title, description, materii, type, source, confidence, created_at) VALUES
  (gen_random_uuid(), 'Configurarea unui router Cisco ÃƒÂ®n Packet Tracer implicÃ„Æ’ setarea IP Ãˆâ„¢i deschiderea interfeÃˆâ€ºelor', 'Routerele Cisco se configureazÃ„Æ’ iniÃˆâ€ºial prin portul consolÃ„Æ’, apoi se seteazÃ„Æ’ adresa IP Ãˆâ„¢i se activeazÃ„Æ’ interfaÃˆâ€ºa cu ''no shutdown''.', ARRAY['RetelisticÃ„Æ’'], 'algorithm', 'Lab4.pdf', 'supported', NOW()),
  (gen_random_uuid(), 'Conversia continuu-discret ÃƒÂ®n MATLAB foloseÃˆâ„¢te funcÃˆâ€ºia c2d', 'FuncÃˆâ€ºia c2d(sys, T, method) converteÃˆâ„¢te un sistem continuu ÃƒÂ®n discret cu extrapolator de ordin zero Ãˆâ„¢i perioadÃ„Æ’ T.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 4_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Criteriul Liapunov determinÃ„Æ’ stabilitatea prin funcÃˆâ€ºii scalare pozitiv definite', 'Metoda a doua Liapunov: sistemul este stabil dacÃ„Æ’ existÃ„Æ’ o funcÃˆâ€ºie V(x) pozitiv definitÃ„Æ’ cu derivata negativ semidefinitÃ„Æ’.', ARRAY['Sisteme Automate'], 'definition', 'SA Laborator 11-12_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Criteriul Popov verificÃ„Æ’ stabilitatea absolutÃ„Æ’ a sistemelor neliniare', 'Criteriul Popov: sistemul neliniar ÃƒÂ®nchis este absolut stabil dacÃ„Æ’ existÃ„Æ’ q > 0 astfel ÃƒÂ®ncÃƒÂ¢t hodograful modificat H*(jÃâ€°) este situat ÃƒÂ®n semiplanul drept al dreptei Popov.', ARRAY['Sisteme Automate'], 'definition', 'SA Laborator 11-12_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Criteriul Schur-Cohn-Jury verificÃ„Æ’ stabilitatea fÃ„Æ’rÃ„Æ’ calculul polilor', 'Criteriul Jury verificÃ„Æ’ dacÃ„Æ’ rÃ„Æ’dÃ„Æ’cinile polinomului caracteristic P(z) se aflÃ„Æ’ ÃƒÂ®n interiorul cercului unitate prin condiÃˆâ€ºii Ãˆâ„¢i un tabel.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 7_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Discretizarea FOH Ãˆâ„¢i Tustin se implementeazÃ„Æ’ cu c2d Ãˆâ„¢i parametrul method', 'Matlab c2d(sys, Ts, ''foh''|''zoh''|''tustin'') discretizeazÃ„Æ’ sisteme continue. Ts=-1 pentru perioadÃ„Æ’ nespecificatÃ„Æ’.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 8_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'ExerciÃˆâ€ºii de stabilitate prin criteriile rÃ„Æ’dÃ„Æ’cinilor Ãˆâ„¢i Jury', 'ExerciÃˆâ€ºii de verificare a stabilitÃ„Æ’Ãˆâ€ºii sistemelor discrete prin criteriul locului rÃ„Æ’dÃ„Æ’cinilor, Schur-Cohn-Jury Ãˆâ„¢i valori proprii.', ARRAY['Sisteme Automate'], 'example', 'SA Laborator 9_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'EÃˆâ„¢antionarea transformÃ„Æ’ semnalul continuu ÃƒÂ®n secvenÃˆâ€ºÃ„Æ’ discretÃ„Æ’', 'EÃˆâ„¢antionarea converteÃˆâ„¢te x(t) ÃƒÂ®n x[k] la momente kT, iar transformata Z este echivalentul Laplace pentru sisteme discrete.', ARRAY['Sisteme Automate'], 'definition', 'SA Laborator 4_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Identificarea funcÃˆâ€ºiilor de transfer din curbele Nyquist Ãˆâ„¢i Bode', 'Identificarea H(s) din hodograful Nyquist: constanta K, ordinul sistemului, constantele de timp TÃ¢â€šÂ, TÃ¢â€šâ€š din puncte caracteristice.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 14_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Metoda Tustin de discretizare foloseÃˆâ„¢te substituÃˆâ€ºia biliniarÃ„Æ’', 'Transformarea biliniarÃ„Æ’ Tustin substituie s = (2/T)Ã‚Â·(z-1)/(z+1), pÃ„Æ’streazÃ„Æ’ stabilitatea dar deformeazÃ„Æ’ frecvenÃˆâ€ºa.', ARRAY['Sisteme Automate'], 'formula', 'SA Laborator 6_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Metoda ZOH de discretizare menÃˆâ€ºine constantÃ„Æ’ ultima valoare eÃˆâ„¢antionatÃ„Æ’', 'ZOH menÃˆâ€ºine semnalul constant ÃƒÂ®ntre eÃˆâ„¢antioane Ãˆâ„¢i introduce o ÃƒÂ®ntÃƒÂ¢rziere de tact; nu se recomandÃ„Æ’ pentru aproximarea regulatoarelor.', ARRAY['Sisteme Automate'], 'definition', 'SA Laborator 6_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Proiectarea regulatorului PID foloseÃˆâ„¢te metodele Ziegler-Nichols experimentalÃ„Æ’ sau Kessler', 'Regulatorul PID se proiecteazÃ„Æ’ prin metode Ziegler-Nichols, experimentalÃ„Æ’ sau Kessler, cu calculul parametrilor Kp, Ki, Kd.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 3_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Punctele de echilibru Ãˆâ„¢i stabilitatea localÃ„Æ’ a sistemelor neliniare se analizeazÃ„Æ’ prin liniarizare', 'Sistemele neliniare de ordin doi se analizeazÃ„Æ’ prin puncte de echilibru, matrice JacobianÃ„Æ’, valori proprii Ãˆâ„¢i planul fazelor.', ARRAY['Sisteme Automate'], 'definition', 'SA Laborator 10_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Regulatorul Fuzzy foloseÃˆâ„¢te funcÃˆâ€ºii de apartenenÃˆâ€ºÃ„Æ’ Ãˆâ„¢i reguli lingvistice', 'Regulatorul Fuzzy se proiecteazÃ„Æ’ cu 5 funcÃˆâ€ºii de apartenenÃˆâ€ºÃ„Æ’ Ãˆâ„¢i reguli fuzzy, apoi se comparÃ„Æ’ performanÃˆâ€ºele cu PID-ul clasic.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 3_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Simularea reÃˆâ€ºelelor Cisco se realizeazÃ„Æ’ ÃƒÂ®n Packet Tracer cu rutare staticÃ„Æ’ Ãˆâ„¢i subnetare', 'Packet Tracer permite simularea reÃˆâ€ºelelor: configurarea rutelor statice, tabela de rutare Ãˆâ„¢i verificarea conectivitÃ„Æ’Ãˆâ€ºii cu ping.', ARRAY['RetelisticÃ„Æ’'], 'example', 'Lab4.pdf', 'supported', NOW()),
  (gen_random_uuid(), 'SIMULINK discretizeazÃ„Æ’ sisteme cu Zero-Order Hold Ãˆâ„¢i Discrete Transfer Fcn', 'SIMULINK oferÃ„Æ’ blocuri pentru simularea sistemelor discrete: Zero-Order Hold Ãˆâ„¢i Discrete Transfer Fcn cu parametrizare.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 5_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Simulink modeleazÃ„Æ’ funcÃˆâ€ºii de transfer Ãˆâ„¢i rÃ„Æ’spunsul indicial', 'Simulink permite implementarea Ãˆâ„¢i simularea funcÃˆâ€ºiilor de transfer, determinarea rÃ„Æ’spunsului indicial, a erorii staÃˆâ€ºionare Ãˆâ„¢i a suprareglajului.', ARRAY['Sisteme Automate'], 'example', 'SA Laborator 1_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Stabilitatea sistemelor discrete se verificÃ„Æ’ prin criteriul locaÃˆâ€ºiei rÃ„Æ’dÃ„Æ’cinilor ÃƒÂ®n planul z', 'Un sistem discret este stabil BIBO dacÃ„Æ’ toÃˆâ€ºi polii funcÃˆâ€ºiei de transfer se aflÃ„Æ’ ÃƒÂ®n interiorul cercului unitate |z| < 1.', ARRAY['Sisteme Automate'], 'definition', 'SA Laborator 7_2026.pdf', 'established', NOW()),
  (gen_random_uuid(), 'Stabilitatea sistemelor discrete se verificÃ„Æ’ prin valorile proprii ale matricei A', 'Pentru un sistem discret x[k+1] = AÃ‚Â·x[k] + BÃ‚Â·u[k], stabilitatea impune ca toate valorile proprii ale matricei A sÃ„Æ’ aibÃ„Æ’ |ÃŽÂ»| < 1.', ARRAY['Sisteme Automate'], 'algorithm', 'SA Laborator 7_2026.pdf', 'established', NOW());
